# Generated by Django 2.2.5 on 2019-11-29 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('informations', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, null=True)),
                ('task_goal', models.CharField(blank=True, max_length=200)),
                ('task_priority', models.PositiveSmallIntegerField(blank=True)),
                ('task_reason', models.CharField(blank=True, max_length=200)),
                ('task_duration', models.IntegerField(default=1)),
                ('task_informations', models.CharField(blank=True, max_length=200)),
                ('task_done', models.BooleanField(default=False)),
                ('task_user', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_tasks', models.ManyToManyField(to='tasks_app.Task')),
            ],
        ),
    ]
