# Generated by Django 2.2.5 on 2019-09-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_tasks', models.ManyToManyField(to='tasks_app.Task')),
            ],
        ),
    ]
