# Generated by Django 2.2.5 on 2019-09-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='duration',
        ),
    ]
