# Generated by Django 2.2.5 on 2019-09-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(default=1)),
                ('informations', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_informations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='task_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.Goal'),
        ),
    ]
